### PR TITLE
Access modifiers

### PR DESCRIPTION
**Pull request by devmustache**
I was trying to use this framework in my project but the framework's access modifiers was incorrect so consider changing this for the others:

public struct RequestErrorInformation {
  
  /// Error returned from alamofire.
  public let error: Error
  /// Error status code.
  public let statusCode: Int?
  /// More error information, this could be returned error information from backend.
  public let responseBody: JSON
  
  init(error: Error, data: Data?, urlResponse: HTTPURLResponse?) {
    self.error = error
    responseBody = (try? JSON(data: data ?? Data())) ?? JSON()
    statusCode = urlResponse?.statusCode
  }
    
}

### CODE REVIEW

**Comment by yoxisem544** [comment]
I didn't understand your question, if you are using version 2.1.0, please use a newer version 2.1.2!

**Comment by devmustache** [comment]
It was my mistake. I'm using 2.1.2 now. Thanks.

**Comment by yoxisem544** [comment]
There is a newer version 2.2.0 now, I suggest you to try it!

**Comment by marcot91** [comment]
@yoxisem544 Sorry if it's a noob question but I updated code to newer version 2.2.0 and 
I'm trying this: 
    public func perform() -> Promise<ResponseType> {
        return networkClient.performRequest(self).then(execute: responseHandler)
    }

    func requestVerification(clientSecret:String, phoneVerification:String) {

        // TODO: Create some Worker to do the work
        worker.requestPhoneVerification(clientSecret: clientSecret, pVerification: pVerification).perform().then(execute: {[weak self] response -> () in
                if let strongSelf = self {
                       //present something
                }
        }).catch(execute: { error in
            // catch error code
        })
        

And is giving this compile error: Missing argument for parameter #4 in call.
 Do you have an idea? I'm doing the same as in the example project.

**Pull request closed without merging**
